apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
type: Opaque
data:
  SECRET_KEY: c2VjcmV0X2V4YW1wbGU=     # secret example
  APIKEY: YXBpa2V5X2V4YW1wbGU=        # apikey example
