name: Analyse de sécurité Bandit

on:
  push:
    branches: main
  workflow_dispatch:


jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer Bandit
        run: pip install bandit

      - name: Créer dossier pour résultats
        run: mkdir -p resultats_tests

      - name: Lancer Bandit sur le dossier app/
        run: bandit -r app/ -ll -f json -o resultats_tests/bandit-app.json
        continue-on-error: true

      - name: Lancer Bandit sur le dossier streamlit_app/
        run: bandit -r streamlit_app/ -ll -f json -o resultats_tests/bandit-streamlit.json
        continue-on-error: true

      - name: Lancer Bandit sur le dossier tests/
        run: bandit -r tests/ -ll -f json -o resultats_tests/bandit-tests.json
        continue-on-error: true

      - name: Upload Bandit scan results
        uses: actions/upload-artifact@v4
        with:
          name: rapports-bandit
          path: resultats_tests/
          retention-days: 30