name: Scan de sécurité Trivy

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  trivy-scan:
    name: Scan de l'image Docker avec Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Construire toutes les images avec docker-compose
        run: docker compose build

      - name: Créer le dossier pour les rapports
        run: mkdir -p resultats_tests

      - name: Scanner l’image backend
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'backend-app:latest'
          format: 'json'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'resultats_tests/trivy-backend.json'

      - name: Scanner l’image frontend
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'frontend-app:latest'
          format: 'json'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'resultats_tests/trivy-frontend.json'

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: rapports-trivy
          path: resultats_tests/
          retention-days: 30