name: Scan de sécurité Trivy

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  trivy-scan:
    name: Scan de l'image Docker avec Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Construire toutes les images avec docker-compose
        run: docker compose build

      - name: Scanner l’image backend
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'backend-app:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Scanner l’image frontend
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'frontend-app:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Télécharger les résultats Trivy
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-backend
          path: trivy-results-backend.sarif